### ISSUE TITLE
mongodb mongo-express docker-compose.yml

### ISSUE THREAD

**Issue by ismailalabou** [mongo-express/mongo-express-docker#59]
```
Pulling mongo (mongo:3.6.22-xenial)...
3.6.22-xenial: Pulling from library/mongo
4007a89234b4: Pull complete
5dfa26c6b9c9: Pull complete
0ba7bf18aa40: Pull complete
4c6ec688ebe3: Pull complete
6e27db06de4c: Pull complete
bbecf0ce3761: Pull complete
ce97543d924d: Pull complete
7299669aa5f5: Pull complete
e5fda94ce451: Pull complete
3673227c8d34: Pull complete
4bb718560867: Pull complete
c687b7b215c2: Pull complete
858fb3568c68: Pull complete
Digest: sha256:0a514a1da4da907230f62b9feac783d7cfe601ea51cba33398402f171c359256
Status: Downloaded newer image for mongo:3.6.22-xenial
Pulling mongo-express (mongo-express:0.54.0)...
0.54.0: Pulling from library/mongo-express
e95f33c60a64: Pull complete
8ad47429afec: Pull complete
ed32558722b1: Pull complete
b1f8c696047a: Pull complete
ac51d5cab64d: Pull complete
20aee6a49efa: Pull complete
8c46e74838a7: Pull complete
be294c44cfba: Pull complete
Digest: sha256:6ac0e6f0a7b2739a03fd29dc8c66853a57c527a2ba8b5ab7bfa7dae9ecbc7c92
Status: Downloaded newer image for mongo-express:0.54.0
Creating 2020-08-31-docker-compose_react-app_1 ... done
Creating mongo                                 ... done
Creating mongo-express                          ... done
Creating 2020-08-31-docker-compose_api-server_1 ... done
Attaching to 2020-08-31-docker-compose_react-app_1, mongo, mongo-express, 2020-08-31-docker-compose_api-server_1
react-app_1      | yarn run v1.22.5
react-app_1      | $ react-scripts start
mongo            | 2021-03-21T13:41:34.084+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=bfa1f60de773
mongo            | 2021-03-21T13:41:34.085+0000 I CONTROL  [initandlisten] db version v3.6.22
mongo            | 2021-03-21T13:41:34.085+0000 I CONTROL  [initandlisten] git version: 62d9f36d148e4dacfec1ca8fcb110f1cc410336f
mongo            | 2021-03-21T13:41:34.085+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
mongo            | 2021-03-21T13:41:34.085+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo            | 2021-03-21T13:41:34.085+0000 I CONTROL  [initandlisten] modules: none
mongo            | 2021-03-21T13:41:34.085+0000 I CONTROL  [initandlisten] build environment:
mongo            | 2021-03-21T13:41:34.085+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
mongo            | 2021-03-21T13:41:34.085+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo            | 2021-03-21T13:41:34.085+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo            | 2021-03-21T13:41:34.085+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true }, security: { authorization: "enabled" } }
mongo            | 2021-03-21T13:41:34.085+0000 W -        [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
mongo-express    | Waiting for mongo:27017...
mongo            | 2021-03-21T13:41:34.099+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongo            | 2021-03-21T13:41:34.099+0000 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
mongo            | 2021-03-21T13:41:34.099+0000 I STORAGE  [initandlisten] 
mongo            | 2021-03-21T13:41:34.099+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongo            | 2021-03-21T13:41:34.099+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongo            | 2021-03-21T13:41:34.099+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=2580M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
mongo            | 2021-03-21T13:41:38.655+0000 E STORAGE  [initandlisten] WiredTiger error (-31802) [1616334098:655048][1:0x7f0e9534ba40], connection: __log_open_verify, 1028: Version incompatibility detected: unsupported WiredTiger file version: this build requires a maximum version of 2, and the file is version 3: WT_ERROR: non-specific WiredTiger error Raw: [1616334098:655048][1:0x7f0e9534ba40], connection: __log_open_verify, 1028: Version incompatibility detected: unsupported WiredTiger file version: this build requires a maximum version of 2, and the file is version 3: WT_ERROR: non-specific WiredTiger error
mongo            | 2021-03-21T13:41:38.655+0000 E STORAGE  [initandlisten] An unsupported journal format detected - If you are trying to rollback from version 4.0 to 3.6, please re-start a 4.0 binary and cleanly shut it down so that the journal format will be downgraded.
mongo            | 2021-03-21T13:41:38.756+0000 E -        [initandlisten] Assertion: 28595:-31802: WT_ERROR: non-specific WiredTiger error src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 488
mongo            | 2021-03-21T13:41:38.758+0000 I STORAGE  [initandlisten] exception in initAndListen: Location28595: -31802: WT_ERROR: non-specific WiredTiger error, terminating
mongo            | 2021-03-21T13:41:38.762+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
mongo            | 2021-03-21T13:41:38.762+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
mongo            | 2021-03-21T13:41:38.762+0000 I CONTROL  [initandlisten] now exiting
mongo            | 2021-03-21T13:41:38.763+0000 I CONTROL  [initandlisten] shutting down with code:100
mongo exited with code 100
mongo-express    | /docker-entrypoint.sh: line 14: mongo: Try again
mongo-express    | /docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
mongo-express    | Sun Mar 21 13:41:46 UTC 2021 retrying to connect to mongo:27017 (2/5)
api-server_1     | (node:1) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
api-server_1     | (Use `node --trace-deprecation ...` to show where the warning was created)
api-server_1     | Server running on port 5000
api-server_1     | Connection error failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
api-server_1     |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
api-server_1     |   name: 'MongoNetworkError'
api-server_1     | }]
api-server_1     | MongoDB connection error: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
api-server_1     |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
api-server_1     |   name: 'MongoNetworkError'
api-server_1     | }]
api-server_1     |     at Pool.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/topologies/server.js:438:11)
api-server_1     |     at Pool.emit (events.js:315:20)
api-server_1     |     at /usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:562:14
api-server_1     |     at /usr/src/app/node_modules/mongodb/lib/core/connection/pool.js:995:11
api-server_1     |     at /usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:31:7
api-server_1     |     at callback (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:264:5)
api-server_1     |     at Socket.<anonymous> (/usr/src/app/node_modules/mongodb/lib/core/connection/connect.js:294:7)
api-server_1     |     at Object.onceWrapper (events.js:422:26)
api-server_1     |     at Socket.emit (events.js:315:20)
api-server_1     |     at emitErrorNT (internal/streams/destroy.js:106:8)
api-server_1     |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
api-server_1     |     at processTicksAndRejections (internal/process/task_queues.js:80:21)
mongo-express    | /docker-entrypoint.sh: line 14: mongo: Try again
mongo-express    | /docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
react-app_1      | ℹ ｢wds｣: Project is running at http://172.23.0.2/
react-app_1      | ℹ ｢wds｣: webpack output is served from 
react-app_1      | ℹ ｢wds｣: Content not from webpack is served from /usr/src/app/public
react-app_1      | ℹ ｢wds｣: 404s will fallback to /
react-app_1      | Starting the development server...
react-app_1      | 
mongo-express    | Sun Mar 21 13:41:52 UTC 2021 retrying to connect to mongo:27017 (3/5)
react-app_1      | Browserslist: caniuse-lite is outdated. Please run the following command: `npx browserslist --update-db`
mongo-express    | /docker-entrypoint.sh: line 14: mongo: Try again
mongo-express    | /docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
mongo-express    | Sun Mar 21 13:41:58 UTC 2021 retrying to connect to mongo:27017 (4/5)
mongo-express    | /docker-entrypoint.sh: line 14: mongo: Try again
mongo-express    | /docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
mongo-express    | Sun Mar 21 13:42:04 UTC 2021 retrying to connect to mongo:27017 (5/5)
mongo-express    | /docker-entrypoint.sh: line 14: mongo: Try again
mongo-express    | /docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
mongo-express    | Welcome to mongo-express
mongo-express    | ------------------------
mongo-express    | 
mongo-express    | 
mongo-express    | Mongo Express server listening at http://0.0.0.0:8081
mongo-express    | Server is open to allow connections from anyone (0.0.0.0)
mongo-express    | 
mongo-express    | /node_modules/mongodb/lib/server.js:265
mongo-express    |         process.nextTick(function() { throw err; })
mongo-express    |                                       ^
mongo-express    | Error [MongoError]: failed to connect to server [mongo:27017] on first connect
mongo-express    |     at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35)
mongo-express    |     at Pool.emit (events.js:314:20)
mongo-express    |     at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12)
mongo-express    |     at Object.onceWrapper (events.js:421:26)
mongo-express    |     at Connection.emit (events.js:314:20)
mongo-express    |     at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49)
mongo-express    |     at Object.onceWrapper (events.js:421:26)
mongo-express    |     at Socket.emit (events.js:314:20)
mongo-express    |     at emitErrorNT (internal/streams/destroy.js:92:8)
mongo-express    |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
mongo-express exited with code 1
react-app_1      | Compiled with warnings.
react-app_1      |
react-app_1      | ./src/components/Logo.jsx
react-app_1      |   Line 14:17:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
react-app_1      |
react-app_1      | Search for the keywords to learn more about each warning.
react-app_1      | To ignore, add // eslint-disable-next-line to the line before.
react-app_1      |

```

**Comment by BlackthornYugen** [comment]
@ismailalabou can you test if this is still an issue? if so can you provide reproduction steps?
