### ISSUE TITLE
MongoClient constructor error "useUnifiedTopology: true" 

### ISSUE THREAD

**Issue by mahimsafa** [mongo-express/mongo-express-docker#69]
When I am trying to connect to the server it is showing this `"deprecated"` message. I tried to find the `"MongoClient constructor"` but was unable to find it. How can I fix this?

##### Error message here:
```
Welcome to mongo-express
------------------------


(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:7) UnhandledPromiseRejectionWarning: MongoError: command listDatabases requires authentication
    at Connection.<anonymous> (/node_modules/mongodb/lib/core/connection/pool.js:453:61)
    at Connection.emit (events.js:314:20)
    at processMessage (/node_modules/mongodb/lib/core/connection/connection.js:454:10)
    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connection.js:623:15)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ducalpha** [comment]
I got the same warning when running the latest version on Linux and MongoDb 4.4

**Comment by usp1904** [comment]
Can someone please guide me about the resolution for the same issue? I too got the same warning and the port is disabled.

**Comment by mahimsafa** [comment]
I don't know the exact library or method that they used to connect to MongoDB. I found a solution only for MongoClient and Mongoose. But I searched for these packages but didn't find them.

**Comment by JafarAkhondali** [comment]
duplicate https://github.com/mongo-express/mongo-express/issues/720
